User sign up
vinsol-spree-contrib/spree-on-react pull request #17
Opened 2017-10-12 09:37 UTC by saurishkar

2017-10-12 16:29 UTC, MatthewWaite commented
This is great! Thanks for adding this feature, @saurishkar. When are you planning on merging?

2017-10-16 07:03 UTC, ShubhamGupta requested changes

2017-10-16 07:03 UTC, ShubhamGupta commented on src/apis/user.js
> +  		.post('http://spree-ams.herokuapp.com/api/v1/users')
Do not hard-code the URL, tokens and anything else. Use `.env` file for the same.

2017-10-16 07:03 UTC, ShubhamGupta commented on src/components/shared/header.jsx
> +    this.state = { showModal: false, showSignUpModal: false };
Please rename old `showModal` to `showLoginModal`. Make sure the functionality is still running fine.

2017-10-16 07:03 UTC, ShubhamGupta commented on src/components/user-signup.jsx
> +// function validate(values) {
Please remove these comments.

2017-10-16 07:03 UTC, ShubhamGupta commented on src/components/user-signup.jsx
> +                          <button className="button-primary">
`left-align` this button. Just to keep it consistent with the submit button in login form modal.

2017-10-16 07:03 UTC, ShubhamGupta commented on src/containers/user-signup-connector.js
> +	return {
Fix indentation.

2017-10-23 12:27 UTC, ShubhamGupta approved these changes

2017-10-23 12:27 UTC, merged